/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 15 16:29:36 GMT 2022
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AVLTree_ESTest extends AVLTree_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      aVLTree0.insert((-3240));
      aVLTree0.insert(1779);
      aVLTree0.delete(663);
      aVLTree0.insert(0);
      aVLTree0.insert((-791));
      aVLTree0.delete((-791));
      AVLTree.Node aVLTree_Node0 = aVLTree0.getRoot();
      aVLTree0.delete((-935));
      AVLTree.Node aVLTree_Node1 = aVLTree_Node0.left;
      aVLTree_Node0.left = aVLTree_Node1;
      aVLTree0.insert((-450));
      aVLTree_Node0.left.key = (-1467);
      aVLTree_Node0.height = 391;
      aVLTree_Node0.key = (-791);
      aVLTree_Node1.height = (-935);
      aVLTree_Node0.height = (-791);
      aVLTree_Node0.height = 663;
      aVLTree_Node0.key = (-791);
      aVLTree0.insert(391);
      aVLTree0.getBalance(aVLTree_Node0);
      // Undeclared exception!
      try { 
        aVLTree0.insert(0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("AVLTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      assertEquals((-1), aVLTree0.height());
      assertNotNull(aVLTree0);
      
      aVLTree0.delete(202);
      assertEquals((-1), aVLTree0.height());
      
      aVLTree0.delete((-1195));
      assertEquals((-1), aVLTree0.height());
      
      aVLTree0.insert(156);
      assertEquals(0, aVLTree0.height());
      
      aVLTree0.delete((-1195));
      assertEquals(0, aVLTree0.height());
      
      aVLTree0.delete(2572);
      assertEquals(0, aVLTree0.height());
      
      aVLTree0.insert(2572);
      assertEquals(1, aVLTree0.height());
      
      int int0 = aVLTree0.height();
      assertEquals(1, int0);
      assertEquals(1, aVLTree0.height());
      
      AVLTree.Node aVLTree_Node0 = aVLTree0.getRoot();
      assertEquals(1, aVLTree0.height());
      assertNotNull(aVLTree_Node0);
      
      AVLTree.Node aVLTree_Node1 = aVLTree0.find(156);
      assertSame(aVLTree_Node1, aVLTree_Node0);
      assertEquals(1, aVLTree0.height());
      assertNotNull(aVLTree_Node1);
      
      AVLTree.Node aVLTree_Node2 = aVLTree0.getRoot();
      assertSame(aVLTree_Node2, aVLTree_Node0);
      assertSame(aVLTree_Node2, aVLTree_Node1);
      assertEquals(1, aVLTree0.height());
      assertNotNull(aVLTree_Node2);
      
      aVLTree_Node2.height = 736;
      assertEquals(736, aVLTree0.height());
      
      aVLTree_Node2.key = (-1303);
      assertEquals(736, aVLTree0.height());
      
      aVLTree_Node2.height = (-1303);
      assertEquals((-1303), aVLTree0.height());
      
      AVLTree.Node aVLTree_Node3 = aVLTree_Node2.right;
      assertNotSame(aVLTree_Node3, aVLTree_Node2);
      assertNotSame(aVLTree_Node3, aVLTree_Node0);
      assertNotSame(aVLTree_Node3, aVLTree_Node1);
      assertFalse(aVLTree_Node3.equals((Object)aVLTree_Node2));
      assertFalse(aVLTree_Node3.equals((Object)aVLTree_Node0));
      assertFalse(aVLTree_Node3.equals((Object)aVLTree_Node1));
      assertNotNull(aVLTree_Node3);
      
      aVLTree_Node3.key = (-1195);
      assertEquals((-1303), aVLTree0.height());
      
      int int1 = aVLTree0.getBalance(aVLTree_Node3);
      assertSame(aVLTree_Node2, aVLTree_Node0);
      assertSame(aVLTree_Node2, aVLTree_Node1);
      assertNotSame(aVLTree_Node2, aVLTree_Node3);
      assertNotSame(aVLTree_Node3, aVLTree_Node2);
      assertNotSame(aVLTree_Node3, aVLTree_Node0);
      assertNotSame(aVLTree_Node3, aVLTree_Node1);
      assertFalse(int1 == int0);
      assertFalse(aVLTree_Node2.equals((Object)aVLTree_Node3));
      assertFalse(aVLTree_Node3.equals((Object)aVLTree_Node2));
      assertFalse(aVLTree_Node3.equals((Object)aVLTree_Node0));
      assertFalse(aVLTree_Node3.equals((Object)aVLTree_Node1));
      assertEquals(0, int1);
      assertEquals((-1303), aVLTree0.height());
      
      AVLTree.Node aVLTree_Node4 = aVLTree0.getRoot();
      assertSame(aVLTree_Node4, aVLTree_Node2);
      assertSame(aVLTree_Node4, aVLTree_Node0);
      assertNotSame(aVLTree_Node4, aVLTree_Node3);
      assertSame(aVLTree_Node4, aVLTree_Node1);
      assertFalse(aVLTree_Node4.equals((Object)aVLTree_Node3));
      assertEquals((-1303), aVLTree0.height());
      assertNotNull(aVLTree_Node4);
      
      int int2 = 0;
      aVLTree_Node0.right = aVLTree_Node4;
      assertEquals((-1303), aVLTree0.height());
      
      aVLTree0.insert(int2);
      aVLTree0.getBalance(aVLTree_Node0);
      aVLTree0.getBalance(aVLTree_Node0);
      int int3 = 0;
      aVLTree0.delete(int3);
      int int4 = 1144;
      aVLTree0.insert(int4);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      assertEquals((-1), aVLTree0.height());
      assertNotNull(aVLTree0);
      
      aVLTree0.delete((-401));
      assertEquals((-1), aVLTree0.height());
      
      aVLTree0.insert(0);
      assertEquals(0, aVLTree0.height());
      
      AVLTree.Node aVLTree_Node0 = aVLTree0.getRoot();
      assertEquals(0, aVLTree0.height());
      assertNotNull(aVLTree_Node0);
      
      aVLTree_Node0.height = (-1208);
      assertEquals((-1208), aVLTree0.height());
      
      int int0 = aVLTree0.getBalance(aVLTree_Node0);
      assertEquals(0, int0);
      assertEquals((-1208), aVLTree0.height());
      
      aVLTree0.insert((-316));
      assertEquals(1, aVLTree0.height());
      
      int int1 = aVLTree0.getBalance(aVLTree_Node0);
      assertFalse(int1 == int0);
      assertEquals((-1), int1);
      assertEquals(1, aVLTree0.height());
      
      int int2 = aVLTree0.height();
      assertFalse(int2 == int0);
      assertFalse(int2 == int1);
      assertEquals(1, int2);
      assertEquals(1, aVLTree0.height());
      
      int int3 = aVLTree0.height();
      assertFalse(int3 == int0);
      assertTrue(int3 == int2);
      assertFalse(int3 == int1);
      assertEquals(1, int3);
      assertEquals(1, aVLTree0.height());
      
      AVLTree.Node aVLTree_Node1 = aVLTree0.getRoot();
      assertSame(aVLTree_Node1, aVLTree_Node0);
      assertEquals(1, aVLTree0.height());
      assertNotNull(aVLTree_Node1);
      
      int int4 = aVLTree0.getBalance(aVLTree_Node1);
      assertSame(aVLTree_Node1, aVLTree_Node0);
      assertFalse(int4 == int3);
      assertTrue(int4 == int1);
      assertFalse(int4 == int2);
      assertFalse(int4 == int0);
      assertEquals((-1), int4);
      assertEquals(1, aVLTree0.height());
      
      AVLTree.Node aVLTree_Node2 = aVLTree0.find(1);
      assertEquals(1, aVLTree0.height());
      assertNull(aVLTree_Node2);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      assertEquals((-1), aVLTree0.height());
      assertNotNull(aVLTree0);
      
      int int0 = aVLTree0.height();
      assertEquals((-1), int0);
      assertEquals((-1), aVLTree0.height());
      
      aVLTree0.insert(393);
      assertEquals(0, aVLTree0.height());
      
      aVLTree0.delete(1);
      assertEquals(0, aVLTree0.height());
      
      aVLTree0.insert((-1));
      assertEquals(1, aVLTree0.height());
      
      aVLTree0.delete(2400);
      assertEquals(1, aVLTree0.height());
      
      aVLTree0.delete(0);
      assertEquals(1, aVLTree0.height());
      
      aVLTree0.insert(0);
      assertEquals(1, aVLTree0.height());
      
      AVLTree.Node aVLTree_Node0 = aVLTree0.find((-1));
      assertEquals(1, aVLTree0.height());
      assertNotNull(aVLTree_Node0);
      
      AVLTree.Node aVLTree_Node1 = aVLTree0.new Node((-1));
      assertFalse(aVLTree_Node1.equals((Object)aVLTree_Node0));
      assertEquals(1, aVLTree0.height());
      assertNotNull(aVLTree_Node1);
      
      aVLTree_Node0.right = aVLTree_Node1;
      assertEquals(1, aVLTree0.height());
      
      aVLTree_Node0.height = (-1);
      assertEquals(1, aVLTree0.height());
      
      aVLTree_Node0.key = 0;
      assertEquals(1, aVLTree0.height());
      
      aVLTree_Node0.key = 0;
      assertEquals(1, aVLTree0.height());
      
      int int1 = aVLTree0.getBalance(aVLTree_Node0);
      assertNotSame(aVLTree_Node0, aVLTree_Node1);
      assertFalse(aVLTree_Node0.equals((Object)aVLTree_Node1));
      assertFalse(int1 == int0);
      assertEquals(1, int1);
      assertEquals(1, aVLTree0.height());
      
      AVLTree.Node aVLTree_Node2 = aVLTree0.getRoot();
      assertNotSame(aVLTree_Node2, aVLTree_Node0);
      assertNotSame(aVLTree_Node2, aVLTree_Node1);
      assertFalse(aVLTree_Node2.equals((Object)aVLTree_Node0));
      assertFalse(aVLTree_Node2.equals((Object)aVLTree_Node1));
      assertEquals(1, aVLTree0.height());
      assertNotNull(aVLTree_Node2);
      
      aVLTree0.insert((-2601));
      assertEquals(2, aVLTree0.height());
      
      aVLTree_Node2.key = 1;
      assertEquals(2, aVLTree0.height());
      
      AVLTree.Node aVLTree_Node3 = aVLTree0.find(393);
      assertNotSame(aVLTree_Node3, aVLTree_Node2);
      assertNotSame(aVLTree_Node3, aVLTree_Node0);
      assertNotSame(aVLTree_Node3, aVLTree_Node1);
      assertFalse(aVLTree_Node3.equals((Object)aVLTree_Node2));
      assertFalse(aVLTree_Node3.equals((Object)aVLTree_Node0));
      assertFalse(aVLTree_Node3.equals((Object)aVLTree_Node1));
      assertEquals(2, aVLTree0.height());
      assertNotNull(aVLTree_Node3);
      
      AVLTree.Node aVLTree_Node4 = aVLTree0.getRoot();
      assertNotSame(aVLTree_Node4, aVLTree_Node0);
      assertNotSame(aVLTree_Node4, aVLTree_Node3);
      assertSame(aVLTree_Node4, aVLTree_Node2);
      assertNotSame(aVLTree_Node4, aVLTree_Node1);
      assertFalse(aVLTree_Node4.equals((Object)aVLTree_Node0));
      assertFalse(aVLTree_Node4.equals((Object)aVLTree_Node3));
      assertFalse(aVLTree_Node4.equals((Object)aVLTree_Node1));
      assertEquals(2, aVLTree0.height());
      assertNotNull(aVLTree_Node4);
      
      aVLTree0.delete(1);
      assertEquals(2, aVLTree0.height());
      
      int int2 = aVLTree0.getBalance(aVLTree_Node2);
      assertNotSame(aVLTree_Node2, aVLTree_Node0);
      assertNotSame(aVLTree_Node2, aVLTree_Node3);
      assertNotSame(aVLTree_Node2, aVLTree_Node1);
      assertSame(aVLTree_Node2, aVLTree_Node4);
      assertFalse(int2 == int0);
      assertFalse(int2 == int1);
      assertFalse(aVLTree_Node2.equals((Object)aVLTree_Node0));
      assertFalse(aVLTree_Node2.equals((Object)aVLTree_Node3));
      assertFalse(aVLTree_Node2.equals((Object)aVLTree_Node1));
      assertEquals(0, int2);
      assertEquals(2, aVLTree0.height());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      assertEquals((-1), aVLTree0.height());
      assertNotNull(aVLTree0);
      
      aVLTree0.insert((-1511));
      assertEquals(0, aVLTree0.height());
      
      aVLTree0.insert((-3060));
      assertEquals(1, aVLTree0.height());
      
      aVLTree0.insert(536);
      assertEquals(1, aVLTree0.height());
      
      aVLTree0.insert(0);
      assertEquals(2, aVLTree0.height());
      
      aVLTree0.insert(26);
      assertEquals(2, aVLTree0.height());
      
      AVLTree.Node aVLTree_Node0 = aVLTree0.find(26);
      assertEquals(2, aVLTree0.height());
      assertNotNull(aVLTree_Node0);
      
      aVLTree0.delete((-3060));
      assertEquals(2, aVLTree0.height());
      
      AVLTree.Node aVLTree_Node1 = aVLTree0.find((-312));
      assertEquals(2, aVLTree0.height());
      assertNull(aVLTree_Node1);
      
      AVLTree.Node aVLTree_Node2 = aVLTree0.find((-312));
      assertEquals(2, aVLTree0.height());
      assertNull(aVLTree_Node2);
      
      AVLTree.Node aVLTree_Node3 = aVLTree0.find(1);
      assertEquals(2, aVLTree0.height());
      assertNull(aVLTree_Node3);
      
      AVLTree.Node aVLTree_Node4 = aVLTree0.find(0);
      assertNotSame(aVLTree_Node4, aVLTree_Node0);
      assertFalse(aVLTree_Node4.equals((Object)aVLTree_Node0));
      assertEquals(2, aVLTree0.height());
      assertNotNull(aVLTree_Node4);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      assertEquals((-1), aVLTree0.height());
      assertNotNull(aVLTree0);
      
      aVLTree0.insert(0);
      assertEquals(0, aVLTree0.height());
      
      aVLTree0.delete(0);
      assertEquals((-1), aVLTree0.height());
      
      aVLTree0.insert((-1));
      assertEquals(0, aVLTree0.height());
      
      AVLTree.Node aVLTree_Node0 = aVLTree0.getRoot();
      assertEquals(0, aVLTree0.height());
      assertNotNull(aVLTree_Node0);
      
      aVLTree0.delete(0);
      assertEquals(0, aVLTree0.height());
      
      aVLTree0.insert(0);
      assertEquals(1, aVLTree0.height());
      
      aVLTree0.delete(0);
      assertEquals(0, aVLTree0.height());
      
      AVLTree.Node aVLTree_Node1 = aVLTree0.new Node(0);
      assertFalse(aVLTree_Node1.equals((Object)aVLTree_Node0));
      assertEquals(0, aVLTree0.height());
      assertNotNull(aVLTree_Node1);
      
      aVLTree0.insert(0);
      assertEquals(1, aVLTree0.height());
      
      aVLTree_Node0.right = aVLTree_Node1;
      assertEquals(1, aVLTree0.height());
      
      aVLTree0.insert(3589);
      assertEquals(1, aVLTree0.height());
      
      AVLTree.Node aVLTree_Node2 = aVLTree0.find(0);
      assertNotSame(aVLTree_Node2, aVLTree_Node0);
      assertSame(aVLTree_Node2, aVLTree_Node1);
      assertFalse(aVLTree_Node2.equals((Object)aVLTree_Node0));
      assertEquals(1, aVLTree0.height());
      assertNotNull(aVLTree_Node2);
      
      aVLTree_Node0.left = aVLTree_Node2;
      assertEquals(1, aVLTree0.height());
      
      aVLTree_Node2.height = 0;
      assertEquals(0, aVLTree0.height());
      
      aVLTree_Node2.height = (-1);
      assertEquals((-1), aVLTree0.height());
      
      aVLTree_Node2.right = aVLTree_Node0;
      assertEquals((-1), aVLTree0.height());
      
      AVLTree.Node aVLTree_Node3 = aVLTree0.getRoot();
      assertSame(aVLTree_Node3, aVLTree_Node2);
      assertNotSame(aVLTree_Node3, aVLTree_Node0);
      assertSame(aVLTree_Node3, aVLTree_Node1);
      assertFalse(aVLTree_Node3.equals((Object)aVLTree_Node0));
      assertEquals((-1), aVLTree0.height());
      assertNotNull(aVLTree_Node3);
      
      aVLTree_Node2.left = aVLTree_Node0.left;
      assertEquals((-1), aVLTree0.height());
      
      aVLTree_Node0.left.height = 0;
      assertEquals(0, aVLTree0.height());
      
      int int0 = aVLTree0.height();
      assertEquals(0, int0);
      assertEquals(0, aVLTree0.height());
      
      int int1 = aVLTree0.getBalance(aVLTree_Node2);
      assertNotSame(aVLTree_Node2, aVLTree_Node0);
      assertSame(aVLTree_Node2, aVLTree_Node1);
      assertSame(aVLTree_Node2, aVLTree_Node3);
      assertTrue(int1 == int0);
      assertFalse(aVLTree_Node2.equals((Object)aVLTree_Node0));
      assertEquals(0, int1);
      assertEquals(0, aVLTree0.height());
      
      // Undeclared exception!
      aVLTree0.delete(0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      assertEquals((-1), aVLTree0.height());
      assertNotNull(aVLTree0);
      
      aVLTree0.insert(0);
      assertEquals(0, aVLTree0.height());
      
      aVLTree0.delete(0);
      assertEquals((-1), aVLTree0.height());
      
      aVLTree0.delete(1366);
      assertEquals((-1), aVLTree0.height());
      
      aVLTree0.insert(0);
      assertEquals(0, aVLTree0.height());
      
      aVLTree0.insert(1366);
      assertEquals(1, aVLTree0.height());
      
      aVLTree0.delete(1366);
      assertEquals(0, aVLTree0.height());
      
      aVLTree0.insert((-1066));
      assertEquals(1, aVLTree0.height());
      
      aVLTree0.delete(1366);
      assertEquals(1, aVLTree0.height());
      
      // Undeclared exception!
      try { 
        aVLTree0.delete(0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      assertEquals((-1), aVLTree0.height());
      assertNotNull(aVLTree0);
      
      int int0 = 1;
      aVLTree0.insert(1696);
      assertEquals(0, aVLTree0.height());
      
      aVLTree0.insert((-3702));
      assertEquals(1, aVLTree0.height());
      
      aVLTree0.delete((-3702));
      assertEquals(0, aVLTree0.height());
      
      int int1 = 1;
      aVLTree0.insert(1);
      assertEquals(1, aVLTree0.height());
      
      aVLTree0.insert((-1));
      assertEquals(1, aVLTree0.height());
      
      AVLTree.Node aVLTree_Node0 = aVLTree0.find(1);
      assertEquals(1, aVLTree0.height());
      assertNotNull(aVLTree_Node0);
      
      aVLTree0.insert(1056);
      assertEquals(2, aVLTree0.height());
      
      aVLTree0.delete(0);
      assertEquals(2, aVLTree0.height());
      
      aVLTree0.delete(1);
      assertEquals(1, aVLTree0.height());
      
      // Undeclared exception!
      try { 
        aVLTree0.insert((-1));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // duplicate Key!
         //
         verifyException("AVLTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      assertEquals((-1), aVLTree0.height());
      assertNotNull(aVLTree0);
      
      aVLTree0.delete(1436);
      assertEquals((-1), aVLTree0.height());
      
      aVLTree0.insert(1946);
      assertEquals(0, aVLTree0.height());
      
      aVLTree0.insert(3187);
      assertEquals(1, aVLTree0.height());
      
      int int0 = aVLTree0.height();
      assertEquals(1, int0);
      assertEquals(1, aVLTree0.height());
      
      AVLTree.Node aVLTree_Node0 = aVLTree0.getRoot();
      assertEquals(1, aVLTree0.height());
      assertNotNull(aVLTree_Node0);
      
      AVLTree.Node aVLTree_Node1 = aVLTree0.getRoot();
      assertSame(aVLTree_Node1, aVLTree_Node0);
      assertEquals(1, aVLTree0.height());
      assertNotNull(aVLTree_Node1);
      
      aVLTree_Node0.left = aVLTree_Node1;
      assertEquals(1, aVLTree0.height());
      
      int int1 = 615;
      // Undeclared exception!
      aVLTree0.find(615);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      assertEquals((-1), aVLTree0.height());
      assertNotNull(aVLTree0);
      
      int int0 = (-311);
      aVLTree0.insert((-311));
      assertEquals(0, aVLTree0.height());
      
      AVLTree.Node aVLTree_Node0 = aVLTree0.getRoot();
      assertEquals(0, aVLTree0.height());
      assertNotNull(aVLTree_Node0);
      
      AVLTree.Node aVLTree_Node1 = aVLTree0.find((-311));
      assertSame(aVLTree_Node1, aVLTree_Node0);
      assertEquals(0, aVLTree0.height());
      assertNotNull(aVLTree_Node1);
      
      aVLTree_Node0.right = aVLTree_Node1;
      assertEquals(0, aVLTree0.height());
      
      aVLTree_Node0.left = aVLTree_Node0.right;
      assertEquals(0, aVLTree0.height());
      
      // Undeclared exception!
      aVLTree0.delete((-311));
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      assertEquals((-1), aVLTree0.height());
      assertNotNull(aVLTree0);
      
      aVLTree0.insert(1502);
      assertEquals(0, aVLTree0.height());
      
      aVLTree0.delete(0);
      assertEquals(0, aVLTree0.height());
      
      aVLTree0.insert(1);
      assertEquals(1, aVLTree0.height());
      
      int int0 = aVLTree0.height();
      assertEquals(1, int0);
      assertEquals(1, aVLTree0.height());
      
      aVLTree0.insert(0);
      assertEquals(1, aVLTree0.height());
      
      aVLTree0.delete((-834));
      assertEquals(1, aVLTree0.height());
      
      int int1 = aVLTree0.height();
      assertTrue(int1 == int0);
      assertEquals(1, int1);
      assertEquals(1, aVLTree0.height());
      
      aVLTree0.delete(1);
      assertEquals(1, aVLTree0.height());
      
      aVLTree0.delete(1);
      assertEquals(1, aVLTree0.height());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      assertEquals((-1), aVLTree0.height());
      assertNotNull(aVLTree0);
      
      aVLTree0.delete(3799);
      assertEquals((-1), aVLTree0.height());
      
      aVLTree0.insert(2472);
      assertEquals(0, aVLTree0.height());
      
      aVLTree0.insert(0);
      assertEquals(1, aVLTree0.height());
      
      // Undeclared exception!
      try { 
        aVLTree0.delete(2472);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      assertEquals((-1), aVLTree0.height());
      assertNotNull(aVLTree0);
      
      aVLTree0.insert(1);
      assertEquals(0, aVLTree0.height());
      
      aVLTree0.insert((-1));
      assertEquals(1, aVLTree0.height());
      
      aVLTree0.insert(0);
      assertEquals(1, aVLTree0.height());
      
      AVLTree.Node aVLTree_Node0 = aVLTree0.getRoot();
      assertEquals(1, aVLTree0.height());
      assertNotNull(aVLTree_Node0);
      
      AVLTree.Node aVLTree_Node1 = aVLTree0.getRoot();
      assertSame(aVLTree_Node1, aVLTree_Node0);
      assertEquals(1, aVLTree0.height());
      assertNotNull(aVLTree_Node1);
      
      int int0 = aVLTree0.getBalance(aVLTree_Node0);
      assertSame(aVLTree_Node0, aVLTree_Node1);
      assertEquals(0, int0);
      assertEquals(1, aVLTree0.height());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      assertEquals((-1), aVLTree0.height());
      assertNotNull(aVLTree0);
      
      aVLTree0.insert(0);
      assertEquals(0, aVLTree0.height());
      
      aVLTree0.insert((-1097));
      assertEquals(1, aVLTree0.height());
      
      aVLTree0.delete((-1457));
      assertEquals(1, aVLTree0.height());
      
      aVLTree0.insert((-1457));
      assertEquals(1, aVLTree0.height());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      assertEquals((-1), aVLTree0.height());
      assertNotNull(aVLTree0);
      
      aVLTree0.delete((-561));
      assertEquals((-1), aVLTree0.height());
      
      AVLTree.Node aVLTree_Node0 = aVLTree0.getRoot();
      assertEquals((-1), aVLTree0.height());
      assertNull(aVLTree_Node0);
      
      AVLTree.Node aVLTree_Node1 = aVLTree0.find(3090);
      assertEquals((-1), aVLTree0.height());
      assertNull(aVLTree_Node1);
      
      aVLTree0.insert((-561));
      assertEquals(0, aVLTree0.height());
      
      AVLTree.Node aVLTree_Node2 = aVLTree0.getRoot();
      assertEquals(0, aVLTree0.height());
      assertNotNull(aVLTree_Node2);
      
      aVLTree0.insert(3090);
      assertEquals(1, aVLTree0.height());
      
      int int0 = aVLTree0.height();
      assertEquals(1, int0);
      assertEquals(1, aVLTree0.height());
      
      aVLTree0.insert(1748);
      assertEquals(1, aVLTree0.height());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      assertEquals((-1), aVLTree0.height());
      assertNotNull(aVLTree0);
      
      aVLTree0.insert((-1));
      assertEquals(0, aVLTree0.height());
      
      aVLTree0.insert(8);
      assertEquals(1, aVLTree0.height());
      
      aVLTree0.insert(81);
      assertEquals(1, aVLTree0.height());
      
      AVLTree.Node aVLTree_Node0 = aVLTree0.find(81);
      assertEquals(1, aVLTree0.height());
      assertNotNull(aVLTree_Node0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      assertEquals((-1), aVLTree0.height());
      assertNotNull(aVLTree0);
      
      aVLTree0.insert(0);
      assertEquals(0, aVLTree0.height());
      
      aVLTree0.delete((-1762));
      assertEquals(0, aVLTree0.height());
      
      aVLTree0.insert((-1762));
      assertEquals(1, aVLTree0.height());
      
      AVLTree.Node aVLTree_Node0 = aVLTree0.find((-1762));
      assertEquals(1, aVLTree0.height());
      assertNotNull(aVLTree_Node0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      assertEquals((-1), aVLTree0.height());
      assertNotNull(aVLTree0);
      
      aVLTree0.insert(0);
      assertEquals(0, aVLTree0.height());
      
      AVLTree.Node aVLTree_Node0 = aVLTree0.find(0);
      assertEquals(0, aVLTree0.height());
      assertNotNull(aVLTree_Node0);
      
      int int0 = aVLTree0.getBalance(aVLTree_Node0);
      assertEquals(0, int0);
      assertEquals(0, aVLTree0.height());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      assertEquals((-1), aVLTree0.height());
      assertNotNull(aVLTree0);
      
      AVLTree.Node aVLTree_Node0 = aVLTree0.find(977);
      assertEquals((-1), aVLTree0.height());
      assertNull(aVLTree_Node0);
      
      int int0 = aVLTree0.getBalance((AVLTree.Node) null);
      assertEquals(0, int0);
      assertEquals((-1), aVLTree0.height());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      assertEquals((-1), aVLTree0.height());
      assertNotNull(aVLTree0);
      
      aVLTree0.insert(91);
      assertEquals(0, aVLTree0.height());
      
      aVLTree0.insert(3187);
      assertEquals(1, aVLTree0.height());
      
      int int0 = aVLTree0.height();
      assertEquals(1, int0);
      assertEquals(1, aVLTree0.height());
      
      AVLTree.Node aVLTree_Node0 = aVLTree0.getRoot();
      assertEquals(1, aVLTree0.height());
      assertNotNull(aVLTree_Node0);
      
      AVLTree.Node aVLTree_Node1 = aVLTree0.getRoot();
      assertSame(aVLTree_Node1, aVLTree_Node0);
      assertEquals(1, aVLTree0.height());
      assertNotNull(aVLTree_Node1);
      
      aVLTree_Node0.right = aVLTree_Node1;
      assertEquals(1, aVLTree0.height());
      
      AVLTree.Node aVLTree_Node2 = aVLTree0.find(1);
      assertEquals(1, aVLTree0.height());
      assertNull(aVLTree_Node2);
      
      aVLTree_Node0.key = 1;
      assertEquals(1, aVLTree0.height());
      
      int int1 = 672;
      // Undeclared exception!
      try { 
        aVLTree0.delete(int1);
        fail("Expecting exception: StackOverflowError");
      
      } catch(StackOverflowError e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      assertEquals((-1), aVLTree0.height());
      assertNotNull(aVLTree0);
      
      aVLTree0.insert((-345));
      assertEquals(0, aVLTree0.height());
      
      aVLTree0.delete(2090);
      assertEquals(0, aVLTree0.height());
      
      AVLTree.Node aVLTree_Node0 = aVLTree0.getRoot();
      assertEquals(0, aVLTree0.height());
      assertNotNull(aVLTree_Node0);
      
      int int0 = aVLTree0.getBalance(aVLTree_Node0);
      assertEquals(0, int0);
      assertEquals(0, aVLTree0.height());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      assertEquals((-1), aVLTree0.height());
      assertNotNull(aVLTree0);
      
      aVLTree0.insert(0);
      assertEquals(0, aVLTree0.height());
      
      aVLTree0.insert(296);
      assertEquals(1, aVLTree0.height());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      assertEquals((-1), aVLTree0.height());
      assertNotNull(aVLTree0);
      
      int int0 = 0;
      aVLTree0.insert(0);
      assertEquals(0, aVLTree0.height());
      
      // Undeclared exception!
      try { 
        aVLTree0.insert(0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // duplicate Key!
         //
         verifyException("AVLTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      assertEquals((-1), aVLTree0.height());
      assertNotNull(aVLTree0);
      
      AVLTree.Node aVLTree_Node0 = aVLTree0.getRoot();
      assertEquals((-1), aVLTree0.height());
      assertNull(aVLTree_Node0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      assertEquals((-1), aVLTree0.height());
      assertNotNull(aVLTree0);
      
      aVLTree0.delete(0);
      assertEquals((-1), aVLTree0.height());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      assertEquals((-1), aVLTree0.height());
      assertNotNull(aVLTree0);
      
      aVLTree0.insert(1);
      assertEquals(0, aVLTree0.height());
      
      AVLTree.Node aVLTree_Node0 = aVLTree0.find(1837);
      assertEquals(0, aVLTree0.height());
      assertNull(aVLTree_Node0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      assertEquals((-1), aVLTree0.height());
      assertNotNull(aVLTree0);
      
      AVLTree.Node aVLTree_Node0 = aVLTree0.find((-1));
      assertEquals((-1), aVLTree0.height());
      assertNull(aVLTree_Node0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      assertEquals((-1), aVLTree0.height());
      assertNotNull(aVLTree0);
      
      aVLTree0.insert((-2466));
      assertEquals(0, aVLTree0.height());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      aVLTree0.insert((-1680));
      aVLTree0.delete(0);
      aVLTree0.insert((-1));
      aVLTree0.delete(0);
      aVLTree0.insert(0);
      aVLTree0.find((-1));
      aVLTree0.delete((-1));
      assertEquals(1, aVLTree0.height());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      aVLTree0.insert(1696);
      aVLTree0.delete((-3702));
      aVLTree0.insert(1);
      aVLTree0.insert((-1));
      aVLTree0.insert(1056);
      aVLTree0.delete(42);
      aVLTree0.delete(1);
      int int0 = aVLTree0.height();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      aVLTree0.height();
      int int0 = 393;
      aVLTree0.insert(393);
      aVLTree0.delete((-1));
      aVLTree0.insert((-1));
      aVLTree0.delete(0);
      aVLTree0.insert(0);
      aVLTree0.find((-1));
      aVLTree0.getRoot();
      // Undeclared exception!
      try { 
        aVLTree0.insert((-1));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // duplicate Key!
         //
         verifyException("AVLTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      aVLTree0.delete((-561));
      aVLTree0.insert((-561));
      aVLTree0.find(3122);
      aVLTree0.insert(3122);
      aVLTree0.height();
      aVLTree0.insert(1713);
      assertEquals(1, aVLTree0.height());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      aVLTree0.delete(1436);
      aVLTree0.height();
      aVLTree0.getRoot();
      aVLTree0.find(0);
      aVLTree0.delete(1);
      aVLTree0.insert(831);
      aVLTree0.insert(0);
      aVLTree0.find(1460);
      aVLTree0.getBalance((AVLTree.Node) null);
      aVLTree0.insert((-1));
      aVLTree0.find((-1));
      assertEquals(1, aVLTree0.height());
  }
}
